### ISSUE TITLE
voom choosing wrong dependency version

### ISSUE THREAD

**Issue by nanafwu** [LonoCloud/lein-voom#43]
lein voom freshen gives log:
```
REPO-NAME                      1.4.149-20141222_184926-g3c27306 -> 1.4.149-localize-countries-20141215_184811-g6058b14
```

Running `git diff` in `project.clj` gives:
```
-                 ^{:voom {:repo "git@github.com:REPO-NAME" :branch "master"}} [REPO-NAME "1.4.149-20141210_211751-g7bbe431"]
+                 ^{:voom {:repo "git@github.com:REPO-NAME" :branch "BRANCH-A"}} [REPO-NAME "1.4.149-localize-countries-20141215_184811-g6058b14"]
```

Running `git log --graph --decorate --oneline` gives: 
```
* 3c27306 (HEAD, origin/BRANCH-A, BRANCH-A) xx SHOULD HAVE CHOSEN
* 587eb6f 
*   23ba345 (master) Merge branch 'BRANCH-B'
|\  
| * b000b5a (origin/BRANCH-B) 
* |   9272abc Merge branch 'BRANCH-B'
|\ \  
| |/  
| * 851b029 
* |   f895b5e Merging changes from BRANCH-B to master 
|\ \  
| |/  
| * 1cd60a3 
| * 721217a 
| * 7513f82
* |   839fea6 Merge pull request #277 from yummly/localize-countries xx VOOM CHOSE THIS
|\ \  
| * | ef3f5f8 
| * | 602579b 
| * | 6058b14 
| * |   aecfdea Merge branch 'master' into localize-countries
| |\ \  
| |/ / 
```
(added comments about which branch lein should have chosen above)

**Comment by abrooks** [comment]
Thanks for filing this. Sorry for the holiday-induced delay.

If you're still able to reproduce this, I'd ask that you move your `~/.voom-repos` out of the way temporarily with a command like this:

    mv ~/.voom-repos{,.bak}

We'll want to keep the original .voom-repos directory since it may have some useful clues but I have a base suspicion that the issue is state stored in that directory (as opposed to an issue in the "newest version" algorithm in freshen.

**Comment by vgeshel** [comment]
I work with @nanafwu and am able to reproduce. Moving ~/.voom-repos out of the way doesn't make any difference, voom is till choosing incorrect version.

**Comment by abrooks** [comment]
@vgeshel @nanafwu — I'm presuming from the above scrubbed information that this is a private repository? If this can be cloned (perhaps privately), that makes debug much easier. I have a plan for a debug run mode that can provide helpful diagnostic information without the repo itself but it's not written.

Also, which version of lein-voom are you using?

**Comment by abrooks** [comment]
In the interim, I've created and pushed a new version of lein-voom with a command `print-db` which will emit the internal database used in freshen queries. The new version is:

    [lein-voom "0.1.0-20150115_230705-gd96d771"]

The data emitted by the `print-db` command has sha, time, filename, path, project name and version information but no file contents. You can create a database like this, specifying exactly the repo string used in your dependency:

    lein voom print-db git@github.com:jclaggett/seqex.git > seqex-db.edn

After creating the `.edn` file, you can review it to satisfy any concerns you might have and then email it to me at `aaron@brooks1.net` (or if it's large, put it in a private gist and email me the link to the gist).

**Comment by abrooks** [comment]
@vgeshel @nanafwu — Any luck installing the new lein-voom release and grabbing an .edn dump of the problematic repo?

**Comment by vgeshel** [comment]
@abrooks I was able to fix this by incrementing the version of the dependency. that is, i changed the version in project.clj from 1.4.149-SNAPSHOT to 1.4.150-SNAPSHOT and that made voom pick the correct version. I'll email you the .edn dump

**Comment by abrooks** [comment]
@nanafwu @vgeshel Thank you for providing the database dump. It turns out that there's no bug.

There is, however, a confusing behavior which we'll blame squarely on Maven. :)

The issue is that Maven treats `-SNAPSHOT` as a special version qualifier. It sorts before any versions bearing the same semantic version (i.e. `1.2.3-SNAPSHOT` comes before any actual `1.2.3`* versions. In adding `-localize-countries` where you did in the version string, you strayed from the conventional Maven parsing and the trailing `-SNAPSHOT` lost its meaning for Maven versioning.

Your action to bump the incremental version (from `1.4.149` to `1.4.150` was the correct action. The versioning series that you had created was not going to sort sanely going forwards. This is unfortunate but would have happened with any tool fetching newer versions using Maven's version sort logic.

To make this clearer and hopefully point out the pitfalls to other users, I added [a section to the main lein-voom README](https://github.com/LonoCloud/lein-voom#a-note-about-voom-freshen-versions).

This issue was tricky enough that @Chouser and I had to spend some time looking at the versions before we noticed that the versions, themselves, were out of order. I hope this new information helps! Let us know if any of the documentation or behavior is still unclear!
