### ISSUE TITLE
Issues getting started

### ISSUE THREAD

**Issue by sthomp** [LonoCloud/lein-voom#51]
Hi all,

Been trying to get started with voom but been having a couple issues. Hoping someone can help get me off the ground.

I've added the plugin and a new voom dependency to my project.clj. The dependency is a private github repo. 

When I run `lein voom install` I get this error message: 
```
Refusing to continue with dirty working copy. (Hint: Run 'git status')
```

Do I need to commit my changes to project.clj in order to run install?

Also, when I try to run `lein voom build-deps` I get this error:
```
clojure.lang.ExceptionInfo: git error: {:exit 128, :out "", :err "Cloning into '......\nremote: Invalid username or password.\nfatal: Authentication failed for 'https://github.com/...../'\n", :git ("clone" "https://github.com/......" #object[java.io.File 0x162c1dfb "....]), :bool false, :lines nil}
```

I have 2factor auth on my github so I use ssh keys to clone repos. Is this feature supported?

Thanks!

**Comment by abrooks** [comment]
Yes, you need to stash or commit changes in order to run a voom install/deploy.

It looks like either your repo remote or something somewhere in your deps tree is trying to use https (instead of ssh) to fetch the dependencies. With MFA enabled, this will not work. You'll need to be sure that these URIs all use ssh instead of https.

Hope that helps!

**Comment by abrooks** [comment]
Not having heard back, I'm closing this issue.
